### ISSUE TITLE
Dispatching actions is not type safe

### ISSUE THREAD

**Issue by arthurxavierx** [lumihq/purescript-react-basic#71]
The current definition of `Self` allows for actions of any type to be dispatched in some cases, what may cause runtime errors:

```purescript
type Self props state action =
  { props     :: props
  , state     :: state
  , instance_ :: ReactComponentInstance
  }
```

This happens because `action` does not exist in the body of `Self`. A possible solution is to either `newtype` it (breaking change), or change it to:

```purescript
type Self props state action =
  { props     :: props
  , state     :: state
  , instance_ :: ReactComponentInstance
  , action  :: Proxy action
  }
```

**Comment by spicydonuts** [comment]
Should `ReactComponentInstance` have `props state action` phantom types? The only case I can think of where this would happen right now is for a manually-constructed `Self`, not one received from a component lifecycle, and that issue would exist even with the action proxy.

**Comment by arthurxavierx** [comment]
Hm, yes, I believe adding phantom types to `ReactComponentInstance` is a better idea. But it doesn't help only with a manually-constructed `Self`, e.g.:

```purescript
test =
  make (createComponent "Test")
    { initialState: 0
    , update: \self ->
        case _ of
          "" -> Update 0
          _ -> Update (self.state + 1)
    , render: \self ->
        Button.button Button.defaults
          { title = "Test"
          , onPress = capture_ self 1
          }
    }
```

In this example, `action` is `String` in `update`, whereas it is `Int` when using `capture_`.

This happens because `self` is a type synonym, and `action` is a fake phantom type. Phantom types only work with proper types, not synonyms. I believe that adding the proxy to `Self` would solve this without a breaking change.

But adding the phantom types to `ReactComponentInstance` is a way better and safer idea.

**Comment by spicydonuts** [comment]
Oh wow, it seems like type synonyms should warn about unused type parameters then.. Adding the `action` type to `ReactComponentInstance` should fix that as well, since it's a data type, right?

**Comment by arthurxavierx** [comment]
Yes! Adding the phantom types to `ReactComponentInstance` should fix this :)

**Comment by justinwoo** [comment]
Is there a big reason why we can't have the newtype version instead of trying to remove this? This would also make it easier to handle type errors.

**Comment by spicydonuts** [comment]
I tried it and it didn't resolve the issue, but it's possible I was doing it incorrectly. Even without this bug though there were a few people preferring the other approach. I don't mind much either way, I'm more interested in exploring hooks but that's built on a few thing which aren't ready yet.

**Comment by justinwoo** [comment]
I'll have to try looking at this more sometime too. I just don't want to have to change around all of my code, and others on my team really like this approach overal.

**Comment by justinwoo** [comment]
If anything my extensive record setStates have been very unpopular :smile:

**Comment by spicydonuts** [comment]
That's fair haha. I find the actions are more clear, but only because they force you to name your `setState`s. You can do nearly the same thing with `setState`:

Actions:
```purs
update self = case _ of
  Increment -> Update self.state { count = self.state.count + 1 }
  SetTo n -> Update self.state { count = n }

...

send self $ SetTo n
```

SetState:
```purs
increment self = self.setState \s -> s { count = s.count + 1 }
setTo self n = self.setState \s -> s { count = n }

...

setTo self n
self `setTo` n
```

**Comment by spicydonuts** [comment]
I think that pattern makes large components easier to read/learn..

But then hooks aren't so bad either:
```purs
count /\ setCount <- useState 0
let increment = setCount (_ + 1)

...

setCount n
```

or

```purs
state /\ dispatch <-
  useReducer { counter: 0 } \state -> case _ of
    Increment -> state { counter = state.counter + 1 }
    SetTo n -> state { counter = n }

...

dispatch $ SetTo n
...

setCount n
```
